name: Docker Image Build and Publish

on:
  push:
    branches:
      - main  # 触发 workflow 的分支，可以修改为你自己的主分支
  workflow_dispatch: # 手动触发 workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile  # Dockerfile 路径，如果你的 Dockerfile 在其他位置，请修改
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }} # 根据实际情况修改镜像名称和标签
            docker.io/${{ secrets.DOCKER_USERNAME }}/your-image-name:latest  # 构建并推送 latest 标签
